### ISSUE TITLE
is the THRAWS dataset really RAW S2 images ?

### ISSUE THREAD

**Issue by DhDeepLIT** [ESA-PhiLab/PyRawS#25]
Hello guys, 

I have downloaded the THRAWS dataset to play with but I have found that the so called "L0" are the images that have been 
corrected of dark signal non uniforminy and probably corrected of the pixel responses non uniformity ...
The "Raws" here is more about the product being not band registered and reprojected, right ?

Do you plan to realease the real RAWS data at some point ?

Regards, 

François

**Comment by sirbastiano** [comment]
Hi François,
You are right, these are not completely L0 data but the data as much close to it. We call it RAW. 
Major details can be found here: https://arxiv.org/abs/2305.11891

**Comment by GabrieleMeoni** [comment]
Hi François,

I'm sorry for not getting back to you sooner, but we completely missed this issue. In addition to Roberto's response, please notice that our Raw data are decompressed L0 + additional metadata files generated at ground-segment level. As fully disclosed [here](https://github.com/ESA-PhiLab/PyRawS/blob/main/README.md#about-the-project), the main difference with respect to the original raw data is the effect of onboard equalization (to optimize compression) and information loss due to compression. Concerning onboard calibration (gain corrections, removal of dark signals, etc.), this happens periodically when Sentinel-2 is in eclipse at the North Pole, so it is not an additional operation in the data processing chain: https://sentinel.esa.int/documents/247904/2047089/Sentinel-2_Cal-Val_Phase-E2

 So, we provide the closest data to the original "raw" data you can get without interfering with the normal satellite concept of operations.

**Comment by GabrieleMeoni** [comment]
Hi François, 

The algorithm to perform the equalization is described here: https://sentinel.esa.int/documents/247904/2047089/Sentinel-2_Cal-Val_Phase-E2.

Unfortunately, currently we do not have access to the equalization coefficients needed to revert the process. 

Regards,

Gabriele
